package com.ninni.species.client.animation;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

@Environment(EnvType.CLIENT)
public class TreeperAnimations {

        public static final AnimationDefinition PLANTS = AnimationDefinition.Builder.withLength(6f)
                .addAnimation("leftArm",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.0416765f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.375f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.583433f, KeyframeAnimations.posVec(0f, -33f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("rightArm",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.583433f, KeyframeAnimations.posVec(0f, -33f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("rightLeg",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(1.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.625f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.583433f, KeyframeAnimations.posVec(0f, -33f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("leftLeg",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.0416765f, KeyframeAnimations.posVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.1676665f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.583433f, KeyframeAnimations.posVec(0f, -33f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("trunk",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, -2f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1f, KeyframeAnimations.posVec(0f, 8f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 8f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.625f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9167667f, KeyframeAnimations.posVec(0f, -5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.875f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.0416765f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.1676665f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.375f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.625f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.7916765f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.9167665f, KeyframeAnimations.posVec(0f, -5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(4.083433f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.583433f, KeyframeAnimations.posVec(0f, -15f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.75f, KeyframeAnimations.posVec(0f, -16f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.958343f, KeyframeAnimations.posVec(0f, -15f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("trunk",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 27.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 27.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("leftEye",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1f, KeyframeAnimations.posVec(2f, 2f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3433333f, KeyframeAnimations.posVec(2f, 2f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4583433f, KeyframeAnimations.posVec(-1.19f, -2.19f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.8343335f, KeyframeAnimations.posVec(0f, 0f, 6f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("rightEye",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1f, KeyframeAnimations.posVec(2f, 2f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3433333f, KeyframeAnimations.posVec(2f, 2f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4583433f, KeyframeAnimations.posVec(-1.19f, -2.19f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.7916765f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 6f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("canopy",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(5.791677f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("canopy",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, -20f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR))).build();


        public static final AnimationDefinition SHAKE_FAIL = AnimationDefinition.Builder.withLength(0.2916767f)
                .addAnimation("trunk",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 1.25f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR))).build();


        public static final AnimationDefinition SHAKE_SUCCESS = AnimationDefinition.Builder.withLength(0.8343334f)
                .addAnimation("trunk",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("trunk",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-6.12f, 21.69f, -16.17f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-5.73f, -29.5f, 11.51f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0.22f, -2.49f, -5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-0.22f, 5f, -2.51f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("canopy",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 15f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, -35f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 12.5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -20f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR))).build();

}
